baseURL: https://pcpg.github.io/moinho/
languageCode: ja
title: "moinho, nyanpen 2019"
publishDir: docs
canonifyurls: true
pygmentsstyle: 'monokai'
paginate: 6
theme: novela
social:
  blogger: "http://56qua.blogspot.com"
taxonomies:
  author: authors

