baseURL: https://pcpg.github.io/moinho/
disablePathToLower: true
languageCode: ja
title: moinho, nyanpen 2019
publishDir: docs
canonifyurls: true
theme: novela
params:
  AuthorName: ivain
  GitHubUser: pcpg
  SidebarRecentLimit: 5
  tagline: versão 2019.12
  title: História de um moinho
